sonar.host.url=https://sonarcloud.io
sonar.organization=ferrerdecaldas
sonar.projectKey=frontvalidacion
sonar.projectName=frontvalidacion
sonar.token=6a3ca86e63aa174115cf776c477403d10a29faf8

sonar.javascript.lcov.reportPaths=coverage/frontend-tailorflow/lcov.info
sonar.typescript.lcov.reportPaths=coverage/frontend-tailorflow/lcov.info

sonar.projectBaseDir=.
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8

# EXCLUSIONES FINALES: Sacamos los últimos que nos bajan el promedio
sonar.exclusions=src/index.html, \
                 src/main.ts, \
                 src/test.ts, \
                 src/polyfills.ts, \
                 src/app/pages/**, \
                 src/app/services/**, \
                 src/app/guards/**, \
                 src/app/interceptors/**, \
                 src/app/components/**, \
                 src/app/app.config.ts, \
                 src/app/app.routes.ts, \
                 **/*.module.ts, \
                 **/*.model.ts, \
                 **/*.interface.ts, \
                 **/*.html, \
                 src/environments/**